<a href="https://colab.research.google.com/github/Shankars57/DATAWAREHOUSE/blob/main/Copy_of_Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data = [[1,2,3],[4,5,6]]
data
arr = np.array(data)
arr
print(arr," arr shape :-",arr[:,1])

[[1 2 3]
 [4 5 6]]  arr shape :- [2 5]


In [ ]:
data1 = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(data1)
print(arr[:2,1:3])

[[2 3]
 [5 6]]


In [ ]:
arr[:1].transpose()
print(arr[:1].transpose(),arr[:2].transpose())

[[1]
 [2]
 [3]] [[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np
data3 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12],
 [13,14,15],[16,17,18]]
arr3 = np.array(data3)
arr3 = arr.swapaxes(0,1)
print(arr3[:1,:])

[[[ 1  2  3]
  [10 11 12]]]


In [ ]:
import numpy as np
data = [[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]
arr = np.array(data)
print('\n \n')
res = arr[1][:2,:2]
print(res)


 

[[10 11]
 [13 14]]
